# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: GoRadius

on:
  push:
    branches: [ master, development, feature/* ]
  pull_request:
    branches: [ master ]

jobs:
  Test:
    name: Test package against last 3 Go versions
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        rust: [1.18, 1.19, 1.20]
        os:   [ubuntu-20.04]
    steps:
    - name: Set up Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Run tests
      run: go test -v ./...
